import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import MyProvider from "@/redux/MyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dorcus-eshop",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyProvider>
          {/* <QueryClientProvider client={queryClient}> */}
          {children}
          {/* </QueryClientProvider> */}
        </MyProvider>
      </body>
    </html>
  );
}
