type CustomerOrder = {
  key: string;
  customerName: string;
  email: string;
  status: string;
  datesJoined: string;
  noOrders: number;
  noProducts: number;
  total: number;
};

export const customerOrders: CustomerOrder[] = [
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Disabled",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Banned",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    customerName: "Emma Smith",
    email: "emmasmith@email.com",
    status: "Active",
    datesJoined: "10 Nov 2023, 6:05 pm",
    noOrders: 27,
    noProducts: 40,
    total: 1768,
  },
];
