interface OrderProps {
  key: string;
  customerName: string;
  orderId: string | number;
  status: string;
  total: number | string;
  dateAdded: string;
  dateModified: string;
  userImage: string;
}

const orderId: number = Math.round(Math.random() * 10000);

export const orders: OrderProps[] = [
  {
    key: "1",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "2",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "3",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Processing",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "4",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "5",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "6",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Pending",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "7",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "8",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Refunded",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "9",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "10",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Denied",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "11",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "12",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Expired",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "13",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Cancelled",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "14",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Delivering",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "15",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Failed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "16",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "17",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Completed",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
  {
    key: "18",
    customerName: "Pato Ranking",
    orderId: orderId,
    status: "Delivered",
    total: 240,
    dateAdded: "26/01/2023",
    userImage: `${window.location.origin}/assets/images/man_image.png`,
    dateModified: "03/03/2023",
  },
];
