interface DataProps {
  key: string;
  productName: string;
  productId: string;
  qty: number;
  price: number;
  status: string;
  image: string;
}

export const products: DataProps[] = [
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "1",
    price: 200,
    status: "Inactive",
    key: "1",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "2",
    price: 200,
    status: "Inactive",
    key: "2",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "3",
    price: 200,
    status: "Inactive",
    key: "3",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "4",
    price: 200,
    status: "Inactive",
    key: "4",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "5",
    price: 200,
    status: "Inactive",
    key: "5",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "6",
    price: 200,
    status: "Inactive",
    key: "6",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "7",
    price: 200,
    status: "Inactive",
    key: "7",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "8",
    price: 200,
    status: "Inactive",
    key: "8",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "9",
    price: 200,
    status: "Published",
    key: "9",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "10",
    price: 200,
    status: "Inactive",
    key: "10",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "11",
    price: 200,
    status: "Inactive",
    key: "11",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "12",
    price: 200,
    status: "Sheduled",
    key: "12",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "13",
    price: 200,
    status: "Inactive",
    key: "13",
  },
  {
    image: `${window.location.origin}/assets/images/watch.webp`,
    productName: "Smart Watch",
    // discount: "Percentage",
    qty: 40,
    productId: "14",
    price: 200,
    status: "Published",
    key: "14",
  },
];
