type ReturnsProps = {
  key: string;
  date: string;
  noOrdersReturned: number;
  noOrdersRefuned: number;
  noOrdersReplaced: number;
  totalRefunded: number;
  totalReplaced: number;
};

export const returns: ReturnsProps[] = [
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
  {
    key: `${Math.round(Math.random() * 10000)}`,
    date: "Sep 22, 2023",
    noOrdersReturned: 2,
    noOrdersRefuned: 0,
    noOrdersReplaced: 2,
    totalRefunded: 0,
    totalReplaced: 45,
  },
];
